<a href="https://colab.research.google.com/github/shtaleghani/economic-complexity/blob/main/calcuting_dependent_variable_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from ecomplexity import ecomplexity
import tqdm
import time
import numba

In [ ]:
pip install ecomplexity

  Created wheel for ecomplexity: filename=ecomplexity-0.5.2-cp37-none-any.whl size=11285 sha256=95bd43d81fc32fcce3021f9f56bb990103f40e18c001812fa0897cec86857f52
  Stored in directory: /root/.cache/pip/wheels/8f/2a/40/2d40ee5a1ea87583c28ba1d190185e5669111d6c2aba64847f
Successfully built ecomplexity


In [ ]:
export       = pd.read_csv('/content/drive/MyDrive/2014/2014.8.11.csv')
#export       = export.fillna('0')
rca_neighbor = pd.read_csv('/content/drive/MyDrive/2014/RCA_neighbor.csv')
max_prox     = pd.read_csv('/content/drive/MyDrive/2014/maxprox.csv')
gdp          = pd.read_csv('/content/drive/MyDrive/2014/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_2001204.csv')
export       = export[['year','location_code','hs_product_code','export_value']]
trade_cols   = {'time':'year', 'loc':'location_code', 'prod':'hs_product_code', 'val':'export_value'}
cdata        = ecomplexity(export, trade_cols)
cdata        = cdata.fillna(0)
gdp          = gdp.fillna(0)
export_2018  = pd.read_csv('/content/drive/MyDrive/2014/2018hs.csv')
export_2018        = export_2018.fillna(0)

2014


In [ ]:
export       = export.values
rca_neighbor = rca_neighbor.values
max_prox     = max_prox.values
gdp          = gdp.values
#export       = export.values
trade_cols   = trade_cols.values
cdata        = cdata.values

export_2018  = export_2018.values

In [ ]:
x_train = np.empty([131432,5],dtype=np.float32)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
pd.DataFrame(cdata)

0     1            2     3   ...         9         10         11         12
0       ABW   101         5000  2014  ...  0.0672607 -0.224157   0.289173   0.279072
1       ABW   102            0  2014  ...  0.0709229 -0.224157 -0.0970414          0
2       ABW   103            0  2014  ...  0.0574982 -0.224157   0.671185          0
3       ABW   104          196  2014  ...  0.0639466 -0.224157  -0.351716  0.0187558
4       ABW   105        99631  2014  ...  0.0791839 -0.224157          0    4.99961
...     ...   ...          ...   ...  ...        ...       ...        ...        ...
209933    0  9703       997472  2014  ...          0         0          0          0
209934    0  9704        30564  2014  ...          0         0          0          0
209935    0  9705         4758  2014  ...          0         0          0          0
209936    0  9706        80160  2014  ...          0         0          0          0
209937    0  9999  1.60571e+09  2014  ...          0         0          0          0

[209938 rows x 13 columns]

In [ ]:
#x_train[:,0] = ((max_prox)[:,4]).copy()
#x_train[:,1] = ((rca_neighbor)[:,3]).copy()
#x_train[:,3] = ((gdp)[:,5]).copy()
#x_train[:,4] = ((export)[:,31]).copy()

In [ ]:
gdp.shape

(265, 13)

In [ ]:
y_train = np.empty([131432,1],dtype=np.float32)

In [ ]:
# y = []
# for i in tqdm.trange(len(export_2018)):
#   expt4 = (((export[:,1] == np.array(export_2018[i,10])) & (export[:,2] == np.array(export_2018[i,21])))*export[:,3]).sum()
#   y.append((export_2018[i,10],export_2018[i,21],export_2018[i,31]-expt4))


# y = []
# for i in tqdm.trange(len(export)):
#   if export[i,3] == 0:
#     continue
#   expt4 = (((export_2018[:,10] == np.array(export[i,1])) & (export_2018[:,21] == np.array(export[i,2])))*export_2018[:,31]).sum()
#   y.append((export[i,1],export[i,2],(np.logexpt4-export[i,3])/export[i,3]))

#y = []
#for i in tqdm.trange(len(export)):
 # if export[i,3] == 0:
  #  continue
  #expt4 = (((export_2018[:,10] == np.array(export[i,1])) & (export_2018[:,21] == np.array(export[i,2])))*export_2018[:,31]).sum()
  #y.append((export[i,1],export[i,2],(np.log(expt4)-np.log(export[i,3]))))

100%|██████████| 131432/131432 [34:40<00:00, 63.19it/s]


In [ ]:
to_be_delet = []
array = export_2018[:,31] == 0
for i in range(len(array)):
  if array[i] == True:
    to_be_delet.append(i)

export_2018 = np.delete(export_2018,to_be_delet,0)


to_be_delet = []
array = export[:,3] == 0
for i in range(len(array)):
  if array[i] == True:
    to_be_delet.append(i)

export = np.delete(export,to_be_delet,0)


y = []
for i in tqdm.trange(len(export)):
  if export[i,3] == 0:
    continue
  expt4 = (((export_2018[:,10] == np.array(export[i,1])) & (export_2018[:,21] == np.array(export[i,2])))*export_2018[:,31]).sum()
  if expt4 == 0:
    continue
  y.append((export[i,1],export[i,2],(np.log(expt4)-np.log(export[i,3]))))

In [ ]:
y = np.array(y)

In [ ]:
#for i in tqmd.trange(len(export_2018)):
#  if export_2018[i,31] == 0:
 #   export_2018[i,31] = 1

#for i in tqmd.trange(len(export)):
  #if export[i,3] == 0:
   # export[i,3] = 1

In [ ]:
len(y)

111077

In [ ]:
# y = np.array(y)
# y = pd.DataFrame(y)
# y.to_csv('/content/drive/MyDrive/2014/regression2_28.12.csv')

In [ ]:
y = pd.read_csv('/content/drive/MyDrive/2014/regression2_28.12.csv').values

In [ ]:
y

array([[0, 0, 'BWA', 101, 2.6527249683439216],
       [1, 1, 'VNM', 101, 6.493315330047121],
       [2, 2, 'BRN', 101, 0.7462203906651528],
       ...,
       [111074, 111074, 'DEU', 9999, -0.07638690668444426],
       [111075, 111075, 'ARE', 9999, -0.3584891672699229],
       [111076, 111076, 'USA', 9999, 0.12629372532429173]], dtype=object)

In [ ]:
y = y.values

In [ ]:
y

array([[0, 0, 'BWA', 101, 2.6527249683439216],
       [1, 1, 'VNM', 101, 6.493315330047121],
       [2, 2, 'BRN', 101, 0.7462203906651528],
       ...,
       [111074, 111074, 'DEU', 9999, -0.07638690668444426],
       [111075, 111075, 'ARE', 9999, -0.3584891672699229],
       [111076, 111076, 'USA', 9999, 0.12629372532429173]], dtype=object)

In [ ]:
max_p = []
for i in tqdm.trange(len(y)):
  max_p.append((((np.array(y[i,2]) == max_prox[:,2]) & (np.array(y[i,3]) == max_prox[:,1]) )*max_prox[:,4]).sum())

Streaming output truncated to the last 5000 lines.

 91%|█████████▏| 101409/111077 [31:11<03:04, 52.53it/s]


 91%|█████████▏| 101415/111077 [31:11<03:02, 52.84it/s]


 91%|█████████▏| 101421/111077 [31:11<03:01, 53.18it/s]


 91%|█████████▏| 101427/111077 [31:11<03:00, 53.46it/s]


 91%|█████████▏| 101433/111077 [31:11<03:32, 45.41it/s]


 91%|█████████▏| 101439/111077 [31:11<03:21, 47.83it/s]


 91%|█████████▏| 101445/111077 [31:11<03:14, 49.40it/s]


 91%|█████████▏| 101451/111077 [31:11<03:08, 50.98it/s]


 91%|█████████▏| 101457/111077 [31:12<03:06, 51.54it/s]


 91%|█████████▏| 101463/111077 [31:12<03:05, 51.95it/s]


 91%|█████████▏| 101469/111077 [31:12<03:04, 52.10it/s]


 91%|█████████▏| 101475/111077 [31:12<03:02, 52.74it/s]


 91%|█████████▏| 101481/111077 [31:12<03:01, 52.89it/s]


 91%|█████████▏| 101487/111077 [31:12<03:06, 51.44it/s]


 91%|█████████▏| 101493/111077 [31:12<03:04, 52.00it/s]


 91%|█████████▏| 101499/111077 [31:12<03:04, 51.99it/s]


 91%|█████████▏| 101

In [ ]:
max_p

[0.3548387096774194,
 0.2857142857142857,
 0.4736842105263158,
 0.2692307692307692,
 0.42105263157894735,
 0.3684210526315789,
 0.4,
 0.4736842105263158,
 0.3,
 0.2926829268292683,
 0.4,
 0.4736842105263158,
 0.42105263157894735,
 0.4736842105263158,
 0.3684210526315789,
 0.4736842105263158,
 0.42105263157894735,
 0.4736842105263158,
 0.4736842105263158,
 0.38461538461538464,
 0.35,
 0.3333333333333333,
 0.3333333333333333,
 0.4736842105263158,
 0.3333333333333333,
 0.3684210526315789,
 0.4736842105263158,
 0.42105263157894735,
 0.3333333333333333,
 0.4736842105263158,
 0.3,
 0.4736842105263158,
 0.3157894736842105,
 0.42105263157894735,
 0.32,
 0.35,
 0.42105263157894735,
 0.2631578947368421,
 0.42105263157894735,
 0.2894736842105263,
 0.35,
 0.3157894736842105,
 0.3333333333333333,
 0.3684210526315789,
 0.38461538461538464,
 0.4736842105263158,
 0.3684210526315789,
 0.3333333333333333,
 0.35,
 0.4736842105263158,
 0.4,
 0.3157894736842105,
 0.4736842105263158,
 0.4736842105263158,
 0

In [ ]:
max_p = np.array(max_p)
max_p = pd.DataFrame(max_p)
max_p.to_csv('/content/drive/MyDrive/2014/x_maxprox_28.12.csv')

In [ ]:
max_p = pd.read_csv('/content/drive/MyDrive/2014/x_maxprox_28.12.csv')

In [ ]:
max_p = max_p.values

In [ ]:
nrca = []
for i in tqdm.trange(len(y)):
  nrca.append((((np.array(y[i,2]) == rca_neighbor[:,1]) & (np.array(y[i,3]) == rca_neighbor[:,2]) )*rca_neighbor[:,3]).sum())

100%|██████████| 111077/111077 [29:56<00:00, 61.82it/s]


In [ ]:
nrca = np.array(nrca)
nrca = pd.DataFrame(nrca)
nrca.to_csv('/content/drive/MyDrive/2014/x_nrca_28.12.csv')

In [ ]:
cdata

array([['ABW', 101, 5000.0, ..., -0.22415741541582124,
        0.28917277302716377, 0.2790721533681727],
       ['ABW', 102, 0.0, ..., -0.22415741541582124, -0.09704144063420861,
        0.0],
       ['ABW', 103, 0.0, ..., -0.22415741541582124, 0.6711852623910314,
        0.0],
       ...,
       [0, 9705, 4758.0, ..., 0.0, 0.0, 0.0],
       [0, 9706, 80160.0, ..., 0.0, 0.0, 0.0],
       [0, 9999, 1605712667.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [ ]:
y

array([[0, 0, 'BWA', 101, 2.6527249683439216],
       [1, 1, 'VNM', 101, 6.493315330047121],
       [2, 2, 'BRN', 101, 0.7462203906651528],
       ...,
       [111074, 111074, 'DEU', 9999, -0.07638690668444426],
       [111075, 111075, 'ARE', 9999, -0.3584891672699229],
       [111076, 111076, 'USA', 9999, 0.12629372532429173]], dtype=object)

In [ ]:
pci = []
for i in tqdm.trange(len(y)):
   pci.append((((np.array(y[i,3]) == cdata[:,1])*cdata[:,8]).sum())/(np.array(y[i,3]) == cdata[:,1]).sum())

Streaming output truncated to the last 5000 lines.

 94%|█████████▍| 104517/111077 [52:50<03:19, 32.83it/s]


 94%|█████████▍| 104521/111077 [52:50<03:19, 32.90it/s]


 94%|█████████▍| 104525/111077 [52:50<03:17, 33.10it/s]


 94%|█████████▍| 104529/111077 [52:50<03:17, 33.21it/s]


 94%|█████████▍| 104533/111077 [52:51<03:16, 33.34it/s]


 94%|█████████▍| 104537/111077 [52:51<03:19, 32.86it/s]


 94%|█████████▍| 104541/111077 [52:51<03:18, 32.96it/s]


 94%|█████████▍| 104545/111077 [52:51<03:17, 33.04it/s]


 94%|█████████▍| 104549/111077 [52:51<03:16, 33.15it/s]


 94%|█████████▍| 104553/111077 [52:51<03:17, 33.09it/s]


 94%|█████████▍| 104557/111077 [52:51<03:36, 30.10it/s]


 94%|█████████▍| 104561/111077 [52:51<03:52, 28.02it/s]


 94%|█████████▍| 104564/111077 [52:52<04:10, 26.03it/s]


 94%|█████████▍| 104567/111077 [52:52<04:06, 26.37it/s]


 94%|█████████▍| 104571/111077 [52:52<03:52, 27.94it/s]


 94%|█████████▍| 104574/111077 [52:52<03:49, 28.35it/s]


 94%|█████████▍| 104

In [ ]:
pci

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan

In [ ]:
pci = np.array(pci)
pci = pd.DataFrame(pci)
pci.to_csv('/content/drive/MyDrive/2014/x_pci_28.12.csv')

In [ ]:
y = pd.read_csv('/content/drive/MyDrive/2014/regression2_28.12.csv')
y = y.values
x_gdp = []
for i in tqdm.trange(len(y)):
  x_gdp.append((((np.array(y[i,2]) == gdp[:,1])*gdp[:,5]).sum()))




  0%|          | 0/111077 [00:00<?, ?it/s]


  2%|▏         | 2639/111077 [00:00<00:04, 26385.56it/s]


  5%|▍         | 5229/111077 [00:00<00:04, 26231.99it/s]


  7%|▋         | 7821/111077 [00:00<00:03, 26135.56it/s]


 10%|▉         | 10620/111077 [00:00<00:03, 26664.38it/s]


 12%|█▏        | 13457/111077 [00:00<00:03, 27152.69it/s]


 15%|█▍        | 16297/111077 [00:00<00:03, 27513.40it/s]


 17%|█▋        | 19000/111077 [00:00<00:03, 27365.75it/s]


 20%|█▉        | 21840/111077 [00:00<00:03, 27665.61it/s]


 22%|██▏       | 24528/111077 [00:00<00:03, 27422.71it/s]


 25%|██▍       | 27288/111077 [00:01<00:03, 27473.75it/s]


 27%|██▋       | 30099/111077 [00:01<00:02, 27660.73it/s]


 30%|██▉       | 32913/111077 [00:01<00:02, 27802.48it/s]


 32%|███▏      | 35658/111077 [00:01<00:02, 27167.89it/s]


 35%|███▍      | 38354/111077 [00:01<00:02, 26501.27it/s]


 37%|███▋      | 40993/111077 [00:01<00:02, 26230.59it/s]


 39%|███▉      | 43609/111077 [00:01<00:02, 25543.62it/

In [ ]:
x_gdp

[16250781587.0,
 186000000000.0,
 17098342541.0,
 75244294275.0,
 244000000000.0,
 48134486625.0,
 2765363128.0,
 4696500000.0,
 27150728124.0,
 53660342160.0,
 67179914026.0,
 19756494435.0,
 47062206678.0,
 40276532541.0,
 19495519600.0,
 22593480000.0,
 12226514722.0,
 78813839984.0,
 10500000000000.0,
 11880434071.0,
 102000000000.0,
 17627003455.0,
 80686854743.0,
 57852399705.0,
 101000000000.0,
 274000000000.0,
 50577769838.0,
 110000000000.0,
 32472363452.0,
 12356482989.0,
 221000000000.0,
 3271808157.0,
 13268458232.0,
 381000000000.0,
 13897804560.0,
 26773473625.0,
 31329367173.0,
 163000000000.0,
 939000000000.0,
 12803445934.0,
 36847643587.0,
 237000000000.0,
 407000000000.0,
 310000000000.0,
 291000000000.0,
 134000000000.0,
 338000000000.0,
 209000000000.0,
 306000000000.0,
 2040000000000.0,
 56901994980.0,
 1480000000000.0,
 48574531942.0,
 201000000000.0,
 33387712766.0,
 47632326088.0,
 2060000000000.0,
 230000000000.0,
 66103853237.0,
 200000000000.0,
 10862944204.

In [ ]:
x_gdp = np.array(x_gdp)
x_gdp = pd.DataFrame(x_gdp)
x_gdp.to_csv('/content/drive/MyDrive/2014/x_gdp_28.12.csv')

In [ ]:
export

array([[2014, 'CIV', 101, 40.0],
       [2014, 'LKA', 101, 134.0],
       [2014, 'BWA', 101, 872.0],
       ...,
       [2014, 'DEU', 9999, 70174562691.0],
       [2014, 'ARE', 9999, 139000000000.0],
       [2014, 'USA', 9999, 156000000000.0]], dtype=object)

In [ ]:
x_expt = []
for i in tqdm.trange(len(y)):
  country,code = y[i,2],y[i,3]
  # print(country,code)
  value = (((np.array(country) == export[:,1]) & (np.array(code) == export[:,2]))*export[:,3]).sum()
  x_expt.append(value)

Streaming output truncated to the last 5000 lines.
100%|██████████| 111077/111077 [43:12<00:00, 42.84it/s]


In [ ]:
x_expt

[872.0,
 1822.0,
 2119.0,
 4000.0,
 4466.0,
 4594.0,
 5000.0,
 5000.0,
 8688.0,
 9796.0,
 11200.0,
 24350.0,
 25702.0,
 28000.0,
 29042.0,
 32500.0,
 37770.0,
 43000.0,
 61051.0,
 61872.0,
 64200.0,
 70778.0,
 76723.0,
 90664.0,
 109629.0,
 117649.0,
 123400.0,
 126624.0,
 151854.0,
 152955.0,
 186335.0,
 189075.0,
 192264.0,
 193900.0,
 200199.0,
 201159.0,
 204549.0,
 209145.0,
 232884.0,
 257395.0,
 262668.0,
 266831.0,
 272481.0,
 281000.0,
 283005.0,
 320217.0,
 406874.0,
 432546.0,
 463159.0,
 511802.0,
 754369.0,
 909828.0,
 911365.0,
 939317.0,
 1220322.0,
 1234003.0,
 1367541.0,
 1406471.0,
 1428359.0,
 1480569.0,
 1797030.0,
 1813355.0,
 1863626.0,
 2081667.0,
 2467480.0,
 3709049.0,
 4105697.0,
 4142723.0,
 4173284.0,
 4192327.0,
 4413637.0,
 4952663.0,
 5052862.0,
 5565493.0,
 7145015.0,
 8818988.0,
 13357657.0,
 13633199.0,
 14490240.0,
 19257986.0,
 20049283.0,
 20210552.0,
 24141422.0,
 27046162.0,
 60260872.0,
 112260770.0,
 117668490.0,
 120978141.0,
 166516379.0,
 209

In [ ]:
x_expt = np.array(x_expt)
x_expt = pd.DataFrame(x_expt)
x_expt.to_csv('/content/drive/MyDrive/2014/x_expt_28.12.csv')

In [ ]:
list_of_2018 = []
list_of_2014 = []
list_of_difference = []
unique_countries = np.array(export[:,1],dtype=str)
unique_countries = np.unique(unique_countries)

for i in tqdm.trange(len(unique_countries)):
  if export[i,3] == 0:
    continue
  country = unique_countries[i]
  total_ex2018 = ((np.array(country) == export_2018[:,10])*export_2018[:,31]).sum()
  total_ex2014 = ((np.array(country) == export[:,1])*export[:,3]).sum()

  list_of_2018.append((unique_countries[i],total_ex2018))
  list_of_2014.append((unique_countries[i],total_ex2014))
  list_of_difference.append((unique_countries[i],(total_ex2018-total_ex2014)/total_ex2014))




  0%|          | 0/168 [00:00<?, ?it/s]


  2%|▏         | 3/168 [00:00<00:06, 24.59it/s]


  4%|▍         | 7/168 [00:00<00:06, 26.31it/s]


  6%|▌         | 10/168 [00:00<00:05, 27.30it/s]


  8%|▊         | 14/168 [00:00<00:05, 28.51it/s]


 11%|█         | 18/168 [00:00<00:05, 29.43it/s]


 12%|█▎        | 21/168 [00:00<00:04, 29.48it/s]


 15%|█▍        | 25/168 [00:00<00:04, 29.94it/s]


 17%|█▋        | 28/168 [00:00<00:04, 29.31it/s]


 18%|█▊        | 31/168 [00:01<00:04, 29.18it/s]


 21%|██        | 35/168 [00:01<00:04, 29.65it/s]


 23%|██▎       | 39/168 [00:01<00:04, 30.00it/s]


 25%|██▌       | 42/168 [00:01<00:04, 29.97it/s]


 27%|██▋       | 45/168 [00:01<00:04, 29.87it/s]


 29%|██▊       | 48/168 [00:01<00:04, 29.74it/s]


 30%|███       | 51/168 [00:01<00:03, 29.64it/s]


 32%|███▏      | 54/168 [00:01<00:03, 29.55it/s]


 34%|███▍      | 57/168 [00:01<00:03, 29.25it/s]


 36%|███▌      | 60/168 [00:02<00:03, 28.79it/s]


 38%|███▊      | 64/168 [00:02<00:03, 2

In [ ]:
unique_countries = np.array(export[:,1],dtype=str)
unique_countries = np.unique(unique_countries)

list_of_gdp_difference = []

for i in tqdm.trange(len(unique_countries)):
  if export[i,3] == 0:
    continue
  country = unique_countries[i]
  value = ((np.array(country) == gdp[:,1])*gdp[:,12]).sum()
  list_of_gdp_difference.append((country,value))




100%|██████████| 168/168 [00:00<00:00, 16323.27it/s]


In [ ]:
list_of_difference = pd.DataFrame(list_of_difference)
list_of_difference.to_csv('/content/drive/MyDrive/2014/difference_exp_28.12.csv')

list_of_gdp_difference = pd.DataFrame(list_of_gdp_difference)
list_of_gdp_difference.to_csv('/content/drive/MyDrive/2014/difference_gdp_28.12.csv')